services:
    app:
      build: .
      ports:
        - "4000:3333"
      env_file:
        - .env
      depends_on:
        - mongo
      networks:
        - loginNetworks
    
    mongo:
      image: mongo:6
      ports:
        - "27017:27017"
      volumes:
         - .:/app
         - /app/node_modules
      networks:
        - loginNetworks
volumes:
  mongo_data:
networks:
  loginNetworks:
